### PR TITLE
feat: interpolate receiver query param

### PR DESCRIPTION
**Pull request by bdeferme**
This allows for dynamic dashboards where the receiver param is a Grafana variable.

### CODE REVIEW

**Comment by bdeferme** [comment]
I'm sorry to bump this but we're kind of waiting for this to be able to use it.

**Comment by bdeferme** [comment]
Seems like a simple change?

**Review by hbollon — APPROVED** [review]
Hi, sorry for the delay. I don't have much time currently to keep an eye on this project :disappointed_relieved: 
I quickly tested and it seems to be good :ok_hand:

**Comment by hbollon** [comment]
I will try to submit a new release tomorrow

**Comment by hbollon** [comment]
Release submitted to Grafana Cloud :ok_hand:

**Pull request merged**
