### PR TITLE
Add label/annotation selector to query editor

### PR DESCRIPTION
**Pull request by njbartlett**
Ocado Technology would like to contribute this change.

We found that the feature in HEAD, where all labels/annotations on the Alerts were translated to columns, was very useful but not scaleable. We have alerts from several different Prometheus metrics, and each metric usually has a number of labels. With a column allocated for every label for every possible alert, the table is unmanageable and most cells are empty.

In this diff, the user can enter a comma-separated list of labels to be used as table columns. The fixed `timestamp` and `severity` columns are still always present. Additionally the user can specify a column selector of `*`, which adds all remaining labels not previously listed.

### CODE REVIEW

**Comment by njbartlett** [comment]
@cryptobioz Have you had a chance to look at this PR?

**Comment by cryptobioz** [comment]
Your PR is really great!
Thanks @njbartlett

**Comment by cryptobioz** [comment]
I just made a new release, a PR has been submitted to add it to the Grafana's plugins repository: https://github.com/grafana/grafana-plugin-repository/pull/276

**Comment by njbartlett** [comment]
Great, thanks!

**Pull request merged**
