### PR TITLE
[WIP] Add support for silences

### PR DESCRIPTION
**Pull request by cryptobioz**

### CODE REVIEW

**Comment by sam-gaylert** [comment]
While looking into this issue on my own, I've found that using the route

```http://localhost:9093/api/v1/alerts?silenced=true&inhibited=true&filter=```

 or even simply 

```http://localhost:9093/api/v1/alerts?silenced=true```

 does not return the silenced alerts that I can otherwise see in alertmanager's front end. However, I can see all silences, expired or active, by using the route 

```http://localhost:9093/api/v1/silences``` 

I am using the most recent versions of alertmanager (0.15.0-rc.1) and prometheus (2.3.0). Could this be some sort of setup issue on my end? Has this problem come up before?

**Comment by cryptobioz** [comment]
The endpoint `/api/v1/alerts?silenced=true` will returns all the alerts including silenced alerts. You can then filter for what you want. I would prefer this endpoint over `/api/v1/silences` because I want to be able to retrieve both firing and silenced alerts.

**Comment by sam-gaylert** [comment]
What would a filter that only shows silenced/suppressed alerts look like? I've tried filtering by the alert_status column using the syntax from the plugin's documentation (alert_status="suppressed"), but that doesn't seem to be working. Is there a way to set an alert label to the status of that alert?

**Comment by yarix** [comment]
is this PR / ticket going to be fixed?
there is a great value in seeing a panel which say "5 active alerts, 3 silenced".
or getting a table with the silencing rules, expirations etc. 

and Thanks for this plugin :)

**Pull request closed without merging**
