### PR TITLE
fix issue regarding grafana 6.7 / cleanup datasource request

### LINKED ISSUE #72: Support grafana 6.7
In [grafana 6.7.0-beta1](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#670-beta1-2020-03-12)  a breaking change has been introduced, that affects this plugin. See [Notice about changes in backendSrv for plugin authors](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#notice-about-changes-in-backendsrv-for-plugin-authors).

With this upgrade, I currently get the following error:
`Window.fetch: HEAD or GET Request cannot have a body.`

### PR DESCRIPTION
**Pull request by cordula-grau**
This fixes #72

Remove data from alert requests since it is already translated to the filter query string.

### CODE REVIEW

**Comment by d9705996** [comment]
I have tested the changes with Grafana 6,.7.1 and confirm they fix #72

**Comment by Wiebelt** [comment]
I can also confirm this fixes #72, awesome, thanks! :+1:

**Comment by drewboswell** [comment]
This does the trick! @cryptobioz , @ScottBrenner can you look into merging this please?

**Comment by checho13cadc** [comment]
Yes, This fix for me un Grafana 6.7.1. Thanks !!

**Comment by aschleifer** [comment]
Is there any chance to see this merged and released soon? We are using this but we would like to stay on released versions.

**Comment by AtebMT** [comment]
I'd like to also see this merged soon. We're using a docker image to run Grafana and it pulls down released versions of the plugins into the container. Rather not worry about patching the plugin and have it overwritten next time we make any changes to the Grafana configuration.

**Comment by dphilpot** [comment]
Please merge, the PR seems to work flawless.

**Comment by HaveFun83** [comment]
@cryptobioz any news here?

**Comment by CAReyes** [comment]
Hello, we are getting this bug as well. Can we get an update as to when this will be merged?
Thanks!

**Comment by mamedin** [comment]
I tested this PR and it works fine with grafana v6.7.2. Nice work, thanks!

**Comment by cryptobioz** [comment]
Thanks @cordula-grau for this PR! Sorry for the delay, I'll publish a new release soon.

**Comment by elcomtik** [comment]
Can you please publish the release?

**Comment by rgarrigue** [comment]
Ping @cryptobioz, please release it now it's merged

**Comment by mwennrich** [comment]
please release :-)

**Comment by cryptobioz** [comment]
The release [0.0.8](https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource/releases/tag/0.0.8) is out! Its addition in the list of official plugins is pending : https://github.com/grafana/grafana-plugin-repository/pull/603

**Pull request merged**
